default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: starter_kit_development

test:
  <<: *default
  database: starter_kit_test

production:
  <<: *default
  database: starter_kit_production
  username: starter_kit
  password: <%= ENV['STARTER_KIT_DATABASE_PASSWORD'] %>
