# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f03e3d1fd6c97a24f986e4db8e34cf45741b1c1665764e8311fddb39bdd21000c93bfd93d5e597f925624d74d96c493e91d624b5bf16dbb25b324484dd07f681

test:
  secret_key_base: 2a1b5422e7cc882eaa0bcbe7dc6609576c356f3e41e87e50b1a3366486667a990214622ac461da147b244312b1b425be84508197c2610174d278ed7dc5810ffd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
